import { create } from "storybook/theming/create";

const fontBase =
  '"Pretendard Variable", Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, "Helvetica Neue", "Segoe UI", "Apple SD Gothic Neo", "Noto Sans KR", "Malgun Gothic", sans-serif';

export const lightTheme = create({
  base: "light",
  brandTitle: "devjaeyoon design system",
  colorPrimary: "#1d4ed8",
  colorSecondary: "#2563eb",
  appBg: "#f7f8f9",
  appContentBg: "#ffffff",
  appHoverBg: "#f3f4f5",
  appPreviewBg: "#f3f4f5",
  appBorderColor: "#dcdee3",
  appBorderRadius: 8,
  fontBase,
  fontCode: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  textColor: "#1a1c20",
  textInverseColor: "#ffffff",
  textMutedColor: "#555d6d",
  barTextColor: "#555d6d",
  barHoverColor: "#1a1c20",
  barSelectedColor: "#1d4ed8",
  barBg: "#ffffff",
  buttonBg: "#ffffff",
  buttonBorder: "#dcdee3",
  booleanBg: "#dcdee3",
  booleanSelectedBg: "#2563eb",
  inputBg: "#ffffff",
  inputBorder: "#dcdee3",
  inputTextColor: "#1a1c20",
  inputBorderRadius: 8,
});

export const darkTheme = create({
  base: "dark",
  brandTitle: "devjaeyoon design system",
  colorPrimary: "#93c5fd",
  colorSecondary: "#60a5fa",
  appBg: "#171717",
  appContentBg: "#171717",
  appHoverBg: "#212121",
  appPreviewBg: "#212121",
  appBorderColor: "#2e2e2e",
  appBorderRadius: 8,
  fontBase,
  fontCode: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  textColor: "#ebebeb",
  textInverseColor: "#171717",
  textMutedColor: "#b8b8b8",
  barTextColor: "#b8b8b8",
  barHoverColor: "#ebebeb",
  barSelectedColor: "#93c5fd",
  barBg: "#171717",
  buttonBg: "#212121",
  buttonBorder: "#2e2e2e",
  booleanBg: "#2e2e2e",
  booleanSelectedBg: "#60a5fa",
  inputBg: "#212121",
  inputBorder: "#2e2e2e",
  inputTextColor: "#ebebeb",
  inputBorderRadius: 8,
});
